- src/compositor/meta-shaped-texture.c
- src/compositor/meta-window-actor.c
- src/meta/meta-shaped-texture.h
To work around a Mali bug, we use a special blend string to
force depth 24 windows to be fully opaque.
This will be reverted as soon as we have a fixed Mali binary.
[endlessm/eos-shell#4385]
> Mali workaround: force opaque windows to appear as opaque

- src/compositor/compositor.c
The experimental API clutter_stage_set_paint_callback() is replaced
with an ::after-paint signal as of Clutter 1.19.5.
https://github.com/endlessm/eos-shell/issues/4788
> Switch to using ClutterStage::after-paint

- src/ui/theme.c
Since GTK+ commit 3a337156d11a86c7, save()/restore() may only be
used for subelements; in this particular case, the change broke
the backdrop state in decorations. Luckily we don't actually need
the save()/restore() pair anyway, as we only touch the context's
state and always set it explicitly.
[endlessm/eos-shell#5205]
> ui: Adapt to GtkStyleContext changes

- src/core/window.c
GTK+ likes to set these, well, _NET_WM_OPAQUE_REGION in particular, to
the same value. Save some expensive and processing when this happens. We
should probably make GTK+ smarter.
Conflicts:
src/x11/window-x11.c
[endlessm/eos-shell#5708]
> window-x11: Fizzle out changes to the three different regions

- src/ui/frames.c
Due to various games that mutter and GTK+ play with each other, the
resolution change isn't actually detected automatically. Give GTK+ a
little helping push when the resolution changes by invalidating the
style context.
I haven't found a way to do this that doesn't involve a deprecated
function. Sorry.
endlessm/eos-shell#5348
> frames: Adapt to font resolution changes at runtime

- src/compositor/meta-shaped-texture.c
This can happen under "normal" circumstances, due to vendor OpenGL
silliness and threading.
[endlessm/eos-shell#5628]
> meta-shaped-texture: Don't globally complain for Cogl errors

- src/compositor/meta-window-actor.c
Totem does full damage and it would be nice to unredirect it at
fullscreen.
We don't consider it because it is an ARGB32 window, however it should
be fine to unredirect given that it is fully opaque. Adjust the logic
with this consideration in mind.
[endlessm/eos-shell#6289]
> window-actor: consider fully opaque ARGB32 windows for unredirection

- src/backends/meta-monitor-manager.c
The mode might not be set at this point, so output->crtc->current_mode
will be NULL.
https://phabricator.endlessm.com/T12266
> MonitorManager: Check pointer before dereferencing

- src/compositor/meta-shadow-factory.c
- src/compositor/meta-shaped-texture.c
- src/compositor/meta-surface-actor.c
- src/compositor/meta-surface-actor.h
- src/compositor/meta-window-actor.c
- src/meta/meta-shadow-factory.h
- src/meta/meta-shaped-texture.h
- src/meta/meta-window-actor.h
This is almost certainly the wrong place to put this, but it
seems that there isn't any sort of framework available for
library consumers to tweak a window's render pipeline. All
the effects that apply to windows are effectively implemented
in terms of ClutterOffscreenEffect.
We shouldn't have to use ClutterOffscreenEffect for something
as simple as this, so don't.
> compositor: Expose backface culling to library consumers

- debian/mutter-common.install
- debian/mutter.install
It's needed by the shell too.
https://phabricator.endlessm.com/T13219
> Install the restart helper in mutter-common

- src/backends/meta-monitor-manager.c
When evaluating the output width and height, only the currently applied
values are considered. This poses a problem for when the overscanned
output reports a different size without the compensation borders.
Also, appearently, we cannot rely on the is_overscanned value to be
updated, since changing the XRandr property triggers multiple apply &
read cycles.
To fix the issue, a simpler approach was taken: simply check if either
the current monitor size or the overscan-adjusted monitor size match
any of the whitelisted sizes.
https://phabricator.endlessm.com/T13812
> monitor-manager: Evaluate adjusted value for overscan whitelist

- src/backends/meta-monitor-manager-private.h
- src/backends/meta-monitor-manager.c
- src/backends/native/meta-monitor-manager-kms.c
- src/backends/x11/meta-monitor-manager-xrandr.c
- src/org.gnome.Mutter.DisplayConfig.xml
And export them in the DBus API since they're useful for
gnome-control-center.
https://bugzilla.gnome.org/show_bug.cgi?id=763832
https://phabricator.endlessm.com/T16337
> backends: Add flags to MetaMonitorMode

- clutter/clutter/evdev/clutter-virtual-input-device-evdev.c
- cogl/cogl/cogl-context.c
- cogl/cogl/cogl-mutter.h
- cogl/cogl/cogl-renderer-private.h
- cogl/cogl/cogl-renderer.c
- cogl/cogl/driver/gl/cogl-util-gl-private.h
- cogl/configure.ac
- configure.ac
- src/backends/native/meta-renderer-native.c
- src/backends/x11/meta-renderer-x11.c
- src/compositor/meta-sync-ring.c
As it was explained more in depth in https://bugzilla.gnome.org/show_bug.cgi?id=781467, changes were needed to get mutter to compile for our 32 bit ARM platform, where we enable the GLESv2 driver.
The changes in this PR includes:
* 2 commit already landed upstream (tokens for the ARB_Robustness extension, CONTEXT_LOST)
* 1 commit from Jonas not to use GLX when using GLES as a baseline to apply my own patches on top
* 1 commit from to allow disabling the synchronization ring when building with the GLESv2 driver
* 2 small commits to fix the build 
* 1 commit to disable debug symbols in the in-tree version of Cogl (very expensive, specially on GLES)
https://phabricator.endlessm.com/T16599
> Fix the build for 32 bit systems enabling the GLESv2 driver

- debian/control
- debian/control.in
- debian/libmutter0i.install
- debian/mutter-common.install
After some internal discussion last week we realized that shipping
this package in the libmutter0i package was wrong, as libmutter*
packages are meant to be parallel installable, and having the helper
there would clearly break this future.
So, to clean things up a little bit, we're moving the helper back
to mutter-common and, as the helper is a binary file, making that
package arch:any, so that we get versions for and Intel and ARM.
Note that we also need to play with Replaces/Breaks rules too, so
that dist-upgrades on development machines will work cleanly too.
https://phabricator.endlessm.com/T17155
> Move mutter-restart-helper back to the mutter-common package

- debian/changelog
- debian/libmutter0i.install
There's no debian package yet for mutter 3.24, so we are simply bumping the version and adapting to the new filename of the mutter library here.
https://phabricator.endlessm.com/T18787
> Update to mutter 3.24

- src/backends/meta-backend.c
- src/backends/meta-monitor-manager-dummy.c
- src/backends/meta-monitor-manager-private.h
- src/backends/meta-monitor-manager.c
- src/backends/meta-monitor.c
- src/backends/meta-monitor.h
- src/backends/native/meta-monitor-manager-kms.c
- src/core/screen.c
- src/core/window.c
- src/tests/monitor-unit-tests.c
This is a partial backport of the X11-related patches from GNOME bug 730551 (see [1]) that allow running mutter in headless mode (no monitors attached) without crashing. This patches are already part of 3.26 so we will drop them as soon as we rebase on top of that version of the shell.
[1] https://bugzilla.gnome.org/show_bug.cgi?id=730551
https://phabricator.endlessm.com/T19389
> Don't crash when running in headless mode

- src/compositor/meta-surface-actor-x11.c
- src/core/constraints.c
- src/core/place.c
- src/core/screen.c
- src/core/window.c
This PR includes a revert of our downstream patch for headless mode, plus a new set of patches by Jonas for mutter (bugs 730551 and 787637), which are currently pending on review upstream.
Please do NOT merge this for now as it would be good to align with upstream as much as possible.
https://phabricator.endlessm.com/T19389
> Align fixes for headless mode with upstream

- src/core/window.c
As opposed to crashing. In this case, letting the caller deal with
it is the best policy, since this is public API.
https://bugzilla.gnome.org/show_bug.cgi?id=788834
> core: Return -1 if meta_window_get_monitor is called on an unmanaged window

- src/core/startup-notification.c
We currently have some issues with flatpak applications that take
too long to run the first time because of the fontconfig cache being
generated on the fly, which is a process that can take up to 20-30
seconds in a slow machine like the Endless One, thus causing quite
some confusion because of the splash screen disappearing early and
the application showing up later on, once the cache is ready.
To workaround this problem while the fontconfig issue is not entirely
solved, we increase this timeout up to 60 seconds, so that the splash
screen won't be killed too early in those cases as per the startup
notification implementation.
https://phabricator.endlessm.com/T13168
> startup-notification: Increase the timout from 15 to 60 seconds

- src/backends/meta-monitor-manager.c
- src/backends/meta-monitor.c
- src/backends/meta-monitor.h
- src/backends/x11/meta-monitor-manager-xrandr.c
- src/org.gnome.Mutter.DisplayConfig.xml
We used to do this via the GetResources method in the past, but since 3.26 that's no longer used by its only client (g-c-c), which is now using GetCurrentState instead. Thus, we need to revert our previous patch and implement this in the new place.
https://phabricator.endlessm.com/T20655
> Expose human-friendly names for resolution modes

- src/backends/meta-monitor-config-manager.c
- src/backends/meta-monitor-config-manager.h
- src/backends/meta-monitor-manager-private.h
- src/backends/meta-monitor-manager.c
- src/backends/native/meta-monitor-manager-kms.c
- src/backends/x11/meta-monitor-manager-xrandr.c
This PR is an attempt to port our downstream-specific bits from 3.24 into 3.26, where the codebase has substantially changed since that previous release. As previously, this implements the basic support to allow enabling/disabling underscanning, which is not perfect since a few features (e.g. Reverting changes) don't work at the moment because of a combination of issues with the Intel driver, which make it fairly difficult to have those bits working reliably.
Note: it should be possible to upstream the first 4 commits, but the codebase affected has also changed significantly in master (compared to this 3.26 baseline), so we'll defer upstreaming until the next rebase.
https://phabricator.endlessm.com/T20655
> Bring back support for underscanning in "crop" mode

- src/backends/meta-backend.c
Centering the pointer at startup causes undesired behaviour if
it ends up hovering over reactive elements, that might react
to that positioning, causing confusion. This is the case of
the login dialog when a list of different users is shown, as
centering the pointer at startup in that case will get the
user in the center of the screen pre-selected, which is not
the expected behaviour (i.e. pre-selecting the first one).
Fix this by simply moving the pointer out of the way, close
to the bottom-right corner, during initialization.
Closes: https://gitlab.gnome.org/GNOME/gnome-shell/issues/157
https://phabricator.endlessm.com/T21426
> backends: Don't center the pointer on initialization

- src/backends/meta-backend.c
As a follow up to the patch from a95cbd0a, we need to make sure
that the pointer is out of the way as well when monitors changed,
since that's the event that will prevail in some cases. Besides,
this is also consistent with what the code before a95cbd0a was,
which initialized the pointer position in the same way both in
this case and in the real_post_init() function.
Closes: https://gitlab.gnome.org/GNOME/gnome-shell/issues/157
> backend: Don't center the pointers on monitor changes

- clutter/clutter/clutter-actor.c
- clutter/clutter/clutter-effect-private.h
- clutter/clutter/clutter-effect.c
If an effect is active and it overrides the paint volume, we should
always recompute the paint volume when requested and not use the
cache, since the paint volume override can change from call to
call depending on what phase of painting we are in. For instance,
if we are part way through painting effects and request the
paint volume, the paint volume should only go up to the current
effect, but in a later call to compute repaint regions, the
paint volume needs to expand to accomadate the effect.
This still involves a lot of recomputation in the case of effects -
in a later clutter version it would be worth adding an API to
allow effects to explicitly recompute and return a new the paint
volume up to the current effect as opposed to recomputing
the cached one. …
> actor: Always recompute paint volumes when effects are applied

- clutter/clutter/clutter-actor.c
Otherwise we'll be stuck with the same paint volume on the last
frame of the given effect, which could be wrong.
https://phabricator.endlessm.com/T23692
> actor: Also recompute paint volume if we recently dropped effects

- src/backends/meta-monitor-config-manager.c
- src/backends/meta-monitor-config-manager.h
- src/backends/meta-monitor-manager.c
When constructing MetaMonitorsConfig objects, store which type
of switch_config they are for (or UNKNOWN if it is not such
type of config).
Stop unconditionally setting current_switch_config to UNKNOWN when
handling monitors changed events. Instead, set it to the switch_config
type stored in the MonitorsConfig in the codepath that updates logical
state. In addition to being called in the hotplug case along the same
code flow that generates monitors changed events, this is also called
in the coldplug case where a secondary monitor was connected before
mutter was started.
When creating the default linear display config, create it as a
switch_config so that internal state gets updated to represent
linear mode when this config is used.
The previous behaviour of unconditionally resetting …
> meta-monitor-manager: use MonitorsConfig to track switch_config

- src/compositor/compositor.c
- src/compositor/meta-plugin-manager.c
- src/compositor/meta-plugin-manager.h
- src/meta/meta-plugin.h
Currently the compositor plugin has no good way of knowing when it's
being unmanaged.
That would not be a problem normally, since compositors usually run
for the whole session, but there are a few caveats:
- gnome-shell (at least under X11) is automatically restarted by
gnome-session if it crashes
- mutter and gnome-shell support being replaced with another instance,
which is very often used in development
Combined with the fact that the compositor will emit a "destroyed"
signal for every window actor just before quitting in those scenarios,
it is useful for clients to be able to distinguish the case where
windows are not really getting destroyed.
This commit adds a new virtual method to MetaPlugin that can be used
for that purpose.
https://phabricator.endlessm.com/T24406
> compositor: add a new plugin function when unmanaged

- meson_options.txt
Jenkins is unable to test it, so disable the tests. We
can't simply pass -D*tests=false since Jenkins also runs
'ninja dist', which runs the tests anyway.
https://phabricator.endlessm.com/T26224
> meson: Disable tests by default

- clutter/clutter/clutter-deform-effect.c
Moving an actor with a ClutterDeformEffect applied flickers because
the depth_testing is enabled if we remove it the deform effects will
work correctly.
Fixes https://gitlab.gnome.org/GNOME/mutter/issues/507
> clutter: LEQUAL depth_testing on ClutterDeformEffect

- src/backends/native/meta-renderer-native-gles3.c
The current implementation of hybrid GPU support in mutter adds a
hard dependency on GLESv3, which breaks when linked against the
Mali GLESv2 library on the endless mini.
Hybrid GPU support, where one GPU renders and another GPU owns the
scanout, doesn't really seem to be a thing on ARM, so break it in
favor of running on the endless mini.
https://phabricator.endlessm.com/T26795
> renderer/native: Break hybrid GPU support on ARM to fix endless mini

- debian/libmutter-4-0.symbols
- debian/rules
Mutter preferentially uses glx + gl3 when available, which ends up
using mesa's software rendering path on the endless mini.
Disabling full GL and GLX forces us into the EGL + GLESv2 path we
need to use our Mali drivers.
Fixes https://phabricator.endlessm.com/T26795
> Build without full GL or GLX on ARM to fix endless mini performance

- meson.build
- src/core/meta-launch-context.c
- src/meson.build
- src/x11/meta-startup-notification-x11.c
Note that this does not skip notifications started from
`gtk_shell_notify_launch` (wayland only) as that method does not contain
enough information to build an app info needed to check the parental
controls settings.
Signed-off-by: Andre Moreira Magalhaes <andre@endlessm.com>
https://phabricator.endlessm.com/T26990
> Skip startup notifications for apps blacklisted by parental controls

- src/x11/meta-x11-display.c
This cherry-picks the commits from https://gitlab.gnome.org/GNOME/mutter/merge_requests/909/commits which fixes an infinite loop issue when setting the keyboard focus on GNOME Shell `CloseDialog::vfunc_focus` which calls `this._dialog.grab_key_focus()` which ends up invoking `vfunc_focus` again.
It also includes 1 extra patch (also from upstream but not in the upstream MR above) that was an ancestor (to avoid conflicts when applying the changes above).
https://phabricator.endlessm.com/T28185
> Fix force quit dialog issue

- clutter/clutter/clutter-actor.c
- clutter/clutter/clutter-stage-private.h
- clutter/clutter/clutter-stage-view-private.h
- clutter/clutter/clutter-stage-view.c
- clutter/clutter/clutter-stage-window.c
- clutter/clutter/clutter-stage-window.h
- clutter/clutter/clutter-stage.c
- clutter/clutter/clutter-stage.h
- clutter/clutter/clutter-text.c
- clutter/clutter/cogl/clutter-stage-cogl.c
- clutter/clutter/cogl/clutter-stage-cogl.h
- cogl/cogl/cogl-clip-stack.c
- cogl/cogl/cogl-clip-stack.h
- cogl/cogl/cogl-context-private.h
- cogl/cogl/cogl-framebuffer.c
- cogl/cogl/cogl-framebuffer.h
- cogl/cogl/cogl-primitives-private.h
- cogl/cogl/cogl-primitives.c
- cogl/cogl/driver/gl/cogl-clip-stack-gl.c
- cogl/cogl/meson.build
- src/compositor/meta-window-group.c
This is a series of cherry-picks that helps Endless OS running on RPI4. The 4 major features being cherry-picked here are:
1. Regional clipping: reduces the amount of swapped regions quite drastically. This brings the biggest  performance improvements.
2. Separate shadowfb: almost no effect, but it's here anyway.
3. Pango attr cache: significant improvement text-heavy actors (opening and closing menus, icon grid, etc)
4. Shallow relayouts: minor improvement, specially when dragging and resizing windows.
> Performance cherry-picks for Raspberry Pi 4

- clutter/clutter/clutter-actor.c
When selecting the pick regions for an actor we were not considering
whether the actor was allocated and that was causing issues where the
preferred width/height of the actor was used when deciding whether
the actor should be considered as a pick target.
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1169
https://phabricator.endlessm.com/T29664
> clutter/actor: Fix pick when actor is not allocated

- clutter/clutter/clutter-click-action.c
Disabling a click action after a button-press but before a
button-release is captured makes ClutterClickAction connect to
captured-event and never disconnect.
This change fixes it by making sure the captured-event is only
processed if the action is still enabled, otherwise releasing
the action (reset state) and propagating the event.
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1170
https://phabricator.endlessm.com/T29682
> clutter/click-action: Do not process captured event if action is disabled

- clutter/clutter/clutter-actor.c
- clutter/clutter/clutter-mutter.h
- clutter/clutter/clutter-paint-context-private.h
- clutter/clutter/clutter-paint-context.c
- clutter/clutter/clutter-stage.c
- clutter/clutter/cogl/clutter-stage-cogl.c
- src/backends/meta-input-settings.c
- src/backends/meta-screen-cast-monitor-stream-src.c
- src/backends/meta-stage-private.h
- src/backends/meta-stage.c
- src/backends/x11/meta-backend-x11.c
- src/backends/x11/meta-stage-x11.c
- src/compositor/meta-shaped-texture-private.h
- src/compositor/meta-shaped-texture.c
- src/compositor/meta-surface-actor.c
- src/compositor/meta-window-actor-x11.c
- src/core/keybindings.c
- src/core/meta-selection-private.h
- src/core/meta-selection.c
- src/core/window.c
- src/x11/meta-x11-selection-output-stream.c
- src/x11/meta-x11-selection.c
A selection of cherry-picks for mutter 3.36. All of them applied cleanly and no regressions were spotted.
I left out all Wayland-related cherry-picks for now, for the sake of reducing the number of cherry-picks.
https://phabricator.endlessm.com/T30428
> 3.36 cherry-picks

- src/backends/meta-monitor-config-manager.c
It is linear config manager created when ensuring configuration.
However, the switch config is not set as LINEAR, but left as UNKNOWN.
This leads switch mode OSD always shows "Join Displays" icon, rather
than the next icon which is "External Only" after connect an external
display and press Super+P once at first time since mutter starts.
This patch moves switch config setting into
meta_monitor_config_manager_create_linear() (and the sibling functions)
to well prepare the monitors config and avoid missing settings.
This is a regression introduced by 149e4d69345a.
https://phabricator.endlessm.com/T30520
Fixes: https://gitlab.gnome.org/GNOME/mutter/-/issues/1362
> monitor-manager: Set switch config when create monitors config

- src/backends/meta-monitor-manager.c
- src/backends/meta-monitor.c
- src/backends/meta-monitor.h
- src/backends/x11/meta-gpu-xrandr.c
- src/org.gnome.Mutter.DisplayConfig.xml
As discussed on the ticket, this will make g-c-c robust to mutter not having this patch (11a913ad23092bab55aba7df3ce696bec143e616). There will be a g-c-c side of this as well.
https://phabricator.endlessm.com/T30174
> T30174 underscan robustness
